### ISSUE TITLE
u wot m8?

### ISSUE THREAD

**Issue by sector-f** [matthunz/twitch-fs#3]
So what exactly is this supposed to do, anyways?
````
} else if offset == 1 {
    reply.add(1, 0, FileType::Directory, &Path::new("u wot m8"));
````

**Comment by matthunz** [comment]
I still haven't figured out how to put anything inside a directory so
that's just some dumb test I made

**Comment by sector-f** [comment]
Well, commenting it out gets rid of those errors (and then just gets us back to directories that don't contain anything)

**Comment by matthunz** [comment]
Ah OK, I think I changed that locally so I'll do a push when I get home
